resolver: lts-13.29

packages:
  - .
  #- ../numhask/numhask-space
  #- ../numhask/numhask
  #- ../numhask/numhask-prelude

extra-deps:
  - tdigest-0.2
  - git: https://github.com/tonyday567/numhask.git
    commit: 7d0d7333b63494069f3338530cd8530ad158400f
    subdirs:
      - numhask
      - numhask-prelude
      - numhask-space
      - numhask-hedgehog
      - numhask-array

allow-newer: true
